### PR TITLE
Update Metaquity to Phyken network

### PR DESCRIPTION
**Pull request by Ekaanth**

### CODE REVIEW

**Comment by 0xKheops** [comment]
Hi @Ekaanth , thank you for your PR

please make sure the logo name is the same as the id of the chain.
in this case it should be `phyken-network-testnet.svg`

also please remove all dist folder files, those are meant to be generated automatically on by CI.

**Comment by Ekaanth** [comment]
Hi @0xKheops do you think it is correct now?

**Comment by Ekaanth** [comment]
Hello @0xKheops and @alecdwm bumping this up for you.

**Comment by Ekaanth** [comment]
Just realized that this PR is on the main branch and I have opened a new PR on v3 branch.
Thanks.

**Pull request closed without merging**
