### PR TITLE
feat: hydradx isUnknownFeeToken

### PR DESCRIPTION
**Pull request by 0xKheops**
to help testing PR on subsquid that adds this property

### CODE REVIEW

**Comment by alecdwm** [comment]
Before updating, could you please add the new field to the schema too?
You can check it locally with `yarn validate`

**Comment by 0xKheops** [comment]
that's new !

**Comment by alecdwm** [comment]
Yeah! 😄

**Review by alecdwm — APPROVED** [review]
Lgtm!

**Pull request merged**
